import "./globals.css";
// import Nav from "@/components/Nav";
// import Header from "@/components/Header";
// import TopLeftImg from "@/components/TopLeftImg";
import MotionWrapper from "@/components/MotionWrapper";
import { Sora } from "next/font/google";
 
//font settings
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className={`page bg-black text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative`}>
        <MotionWrapper>
            {/* <TopLeftImg />
            <Nav />
            <Header /> */}
            {children}
        </MotionWrapper>
          </div>
      </body>
    </html>
  );
}

// import '../styles/globals.css';
// import Layout from "../ components/Layout";
// import Transition from "../components/Transition";

// import { useRouter } from 'next/router';
// import { AnimatePresence, motion } from 'framer-motion';
// function MyApp({ Component, pageProps }) {
// const router = useRouter();
// return(
// < Layout>
// <AnimatePresence mode='wait'>
// <motion.div key={router.route} className='h-full'>
// <Transition />
// <Component {...pageProps} />
// </motion.div>
// </AnimatePresence>
// </Layout>)}
